name: K-Means Clustering - Code Coverage
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run GMA Series Matrix Parser Code Coverage
      run: cd Final\ Systems/K-Means\ Clustering/K-Means\ Clustering && mvn clean verify -Djacoco.skip=false